### ISSUE TITLE
CanJS 4.0

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/canjs#3140]
4.0 release:

Observables:
- [X] - can-define
- [X] - can-map, can-list
- [ ] - can-map-define
- [ ] - can-observe
- [x] - can-route
- [x] - can-route-pushstate

Model:
- [x] - can-connect
- [ ] - can-connect w/ can-observe

View:
- [ ] can-component
- [ ] can-stache
- [ ] can-stache-bindings
- [ ] - can-view-parse w/ removed regexp delimiters 
- [ ] - can-stache-converters
- [ ] - steal-stache

Other:
- [x] - can-fixture
- [ ] - works in Edge
- [ ] - can-control (needs fix to go back to events)
- [ ] - RVM?

4.0 - How much dead code can we remove? What do we want to break?

- Anything "ok" in 3.0 still works.
- @index 
- `can-click`, `can-value`
- can-control processers
- `foo bar` ..
- helpers always pass values ... ~
- {{#each(items)}}

import template from "foo.stache!can-stache3"

NEW WAY OF DOING THINGS 

 - can-element - w/ or w/o shadow DOM 
 - ES class 
 - Observables based on can-define
 - new binding syntaxes 
 - new Connection()
 - stache (cleaned up / removed) AND JSX option

**Comment by matthewp** [comment]
How are we deciding what is going to be in CanJS 4.0?

**Comment by justinbmeyer** [comment]
@matthewp I'm not sure how we are going to decide what's in CanJS 4.0.  For now, this is just a catch-all epic for issues that can not be done w/o breaking changes.

**Comment by frank-dspeed** [comment]
we should add #3145

**Comment by christopherjbaker** [comment]
can this be closed now, @justinbmeyer?
