### ISSUE TITLE
CanJS 3.NEXT Epic

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3277]
A collection of issues for the next "big" release of CanJS.  This release will hopefully not break 3.X compatibility, but will represent a sizable change in how we build apps.  

I feel like it will include the following:

- [ ] - Improvements to [can-connect](https://github.com/canjs/can-connect/issues/288)
- [ ] - Improvements to [can-set](https://github.com/canjs/can-set/issues/54)
- [ ] - The ability to [trace how values are derived](https://github.com/canjs/canjs/issues/3278), from the DOM to the source data.
- [ ] -  [can-element](https://github.com/canjs/can-element/issues/6)
- [ ] - [New templating engine(s)](https://github.com/canjs/canjs/issues/2995) (probably supporting JSX and something stream-compatible).
- [ ] - Decorators that add observability and other cool features to ViewModels and Models based around `class` expressions. [Decorators work in stealJS](https://github.com/stealjs/steal/issues/1039)
- [ ] - ViewModels that only derive from streams.

This epic should be examples of putting all of this together.

**Comment by matthewp** [comment]
> ViewModels that only derive from streams.

What is this? is there a subissue about this?

**Comment by justinbmeyer** [comment]
@matthewp there isn't yet.  I've talked about it a few place.  I'm about to organize this epic and link to all other issues. What is in and out of this issue is 100% up for discussion.

But in short, there's some VMs that could be written as mostly stream-based.  I'd like to explore that:

```js
@defineStream({
  prop : "setable-stream"
  other: function(){
    this.prop.map(() => null);
  }
});
class WeatherVM {

}
```

**Comment by matthewp** [comment]
@phillipskevin @justinbmeyer given that you've decided to do a 4.0, is there any need to keep this issue open here?

**Comment by phillipskevin** [comment]
I would be fine closing this.
