### ISSUE TITLE
Make CanJS easier to debug

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3278]
## Status

- [ ] - `canReflect.getName` and `canReflect.setName`
- [ ] - can-connstruct .getName
- [ ] - can-define .getName
- [ ] - can-observation
- [ ] - can-compute 

__tldr;__ Lets make CanJS easier to debug!  This issue seeks a variety of solutions, including:

- Add `.log()` methods to most user facing types, allowing users to see what's happening.
- Add the ability to trace (and log) how values are derived.  For example, know that a textNode gets its value from a `getter` that gets its value from a map's `first` and `last` property.

> NOTE: The [Queues for error free and traceable code](https://github.com/canjs/canjs/issues/3507) issue provides the ability to log the the tasks that lead to a particular piece of code being written.  It also makes CanJS easier to debug, but is kept as a separate issue because of the amount of changes needed to make it happen.

> This was discussed at a [contributors meeting (15:50)](https://youtu.be/95OX6-qii24?t=15m50s)

## The Problem

Currently, it's hard to understand how a CanJS application works.  Take a small example:

```js
var view = stache(`
  <h1>{{fullName}}</h1>
  <input value:bind="first"/> <input value:bind="last"/>`);

var ViewModel = DefineMap.extend("PersonVM",{
  get fullName() {
    return this.first + " " + this.last;
  },
  first: "string",
  last: "string"
})
var viewModel = new ViewModel();
document.body.appendChild( view(viewModel) );
```

By looking at the h1's textNode, you can't easily know that:
- `{{fullName}}` is from the `fullName` compute on the ViewModel
   - the `fullName` compute comes from `first` and `last` on the ViewModel
     - `first` comes from the first `<input/>`'s value
     - `last` comes from the last `<input/>`'s value

In addition, you can't know what a value affects.  By looking at the first `<input/>`'s value, you can't see that:
- It's used by the ViewModel's `first` property.
- The ViewModel's `first` property is used by the `fullName` compute.
- The `fullName` compute is used by `{{fullName}}`.

It can also be hard to know when something changes.  For example, to log the value of the `fullName` compute, I would need to do something like:

```js
viewModel.on("fullName", function(ev, newValue, oldValue){
  console.log("viewModel.fullName", newValue, "from",oldValue)
})
```
This is even harder if the viewModel is on a component.

This issue looks to solve three problems specifically:

- Understanding the values that affect another value
- Understanding what values a value affects
- Knowing when state has changed

## Proposed Solution

I think the solution should have two components for each problem stated above:

1. `.logX()` functions that print easily understood textual information.
2. `.logXData()` functions that provide the raw data used by `.log` that can be easily used by custom debugging tools (like a canjs chrome developer tool)

Once this is implemented, we will have a tutorial explaining the use of these APIs.

### Understanding the values that affect another value

Given the example above, I propose the following can be used to log `{{fullName}}`'s dependencies:

```js
var debug = require("can-debug");

var fullNameTextNode = document.querySelector("h1").firstChild

debug.logDependencies( fullNameTextNode )
```

This will log:

```
{{fullName}} <textNode> <"Justin Meyer">
  PersonVM(12).fullName <viewModel> <fullNameFunction> <"Justin Meyer">
    PersonVM(12).first <viewModel> <"Justin">
      input.value <input> <"Justin">
    PersonVM(12).last <viewModel> <"Last">
      input.value <input> <"Last">
```

> NOTE: `<VALUE>` means the VALUE is logged.  For example, with`<textNode>` the user will see the textNode object being logged, not the text `<textNode>`.
> Also, `12` is the CID of the viewModel.  

### Understanding what values a value affects

Given the example above, I propose the following can be used to log the first `<input>`'s dep:

```js
var debug = require("can-debug");

var firstInput = document.querySelector("input").firstChild

debug.logDependents( firstInput )
```

This will log:

```
PersonVM(12).first <viewModel> <"Justin">
  input.value <input> <"Justin">                     <--- MEANS IT DEPENDS ON ITSELF!
  PersonVM(12).fullName <viewModel> <fullNameFunction> <"Justin Meyer">
    {{fullName}} <textNode> <"Justin Meyer">
```

### Knowing when state has changed

For most observables, I would like to add a `.log()` function that logs when their value changes.  For example, the following:

```js
vm.log()
```

Would log the following after `first` and `last` changed:

```
PersonVM(12).first <"Payal">
PersonVM(12).last <"Shah">
PersonVM(12).fullName <"Payal Shah">
```

For Maps, you can limit the values like:

```js
vm.log("first")
```

The log method would be present on anything that changes values, including:

- Observation
- Scope
- Compute
- DefineMap
- Stache expressions
- Route
- can-connect instance and listStores

## Steps:

- [x] - [Add a Symbol for decorating Types with a readable name](https://github.com/canjs/can-symbol/issues/16)
- [x] - [Add `log()`/`unlog()` for listening to when a value or key changes](https://github.com/canjs/canjs/issues/3599)
- [x] - [Add logWhatChangesMe method](https://github.com/canjs/can-debug/issues/9)
- [x] - [Add a getMutatedBy Observable reflection](https://github.com/canjs/can-reflect/issues/54)
- [x] - [Add logWhatIChange method](https://github.com/canjs/can-debug/issues/10)
- [x] - [Create debugging guide](https://github.com/canjs/canjs/issues/3600)

**Comment by chasenlehara** [comment]
cc @mjstahl who has been working on https://github.com/donejs/done-inspect

**Comment by matthewp** [comment]
I think the ability to step through state mutations is more useful than the former. You can pretty easily trace from a Node to its source template.

**Comment by justinbmeyer** [comment]
- Common problems
  - Why is something not mutating
  - What caused some mutation
  - Binding to a "leaked" scope vs a binding.
  - Creating loops that recurse
    - Someone uses a setter => Use event streams.
  - Routing
     - can.route -> `{ ... } -> "url"`
  - Stack gets weird with batching -> 2 queues
  - Invalid stache syntax -> better parser.
  - `namespace` collision message.

- Memory leaks
  - people forgetting bindings (binding to things manually) `onKeyValue` `.on`
  - on component initialization .... track bindings ... when it's removed ... check they are undone.

- Techniques
   - Understanding scope
   - Debugging and walking stack
   - Break on change (using a `setter`)
   - How to setup routing rules correctly

- Dev Env 
  - Tell people how to get syntax highlighting for stache

**Comment by justinbmeyer** [comment]
show mutating VM

**Comment by mjstahl** [comment]
Seaside's concept of Halo's was in an inspiration for me working on the done-inspect code, and is a high level goal.

http://seaside.st/about/examples/halos

**Comment by phillipskevin** [comment]
![image](https://user-images.githubusercontent.com/5851984/30656230-ff5bc1ae-9df8-11e7-81b4-e6bd6b717cfc.png)

**Comment by phillipskevin** [comment]
here are the original steps from the description:

- [ ] - Survey DoneJS Community members and Bitovian's about common gotcha problems.
- [ ] - Support tracing through an element to its source value.
- [x] - Support `debugger` in stache so that people can explore the scope.
- [ ] - Write a guide or FAQ on debugging CanJS applications.  Topics:
   - [ ] - Find the origin of a mutation.

**Comment by justinbmeyer** [comment]
As we need convention for logging information for a wide variety of types.  I'm thinking `canReflect.getName()` might return the following:

- Instances of map-likes `Person{}`
- Instances of array-likes `People[]`
- Instances of value-likes `Observation<>`
- Method `Person{}.eat` (This implies we decorated all methods with info on the constructor)

- If we want to provide additional information, like a `cid` or current value, we can do that between `{}`, `[]`, or `<>`

For example, say we have a `can-connect`-ed `Person` type where we know the unique id property.  We might have a instance of person log like:

```js
Person{22}
```

Or say we DO have a CID, then we can use it on those types like:

```
Observation<21>
```

Or maybe an observation logs its value:

```
Observation<"Justin Meyer">
```

A list might have its length:

```js
People[5]
```

**Comment by justinbmeyer** [comment]
Closing as solved in 4.0
