### ISSUE TITLE
CanJS 5.0 Data Layer

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4084]
The following describes a proposal for CanJS 5.0's data layer that reflects the improvements and ideas in can-query.

> This was discussed on a [recent live stream (9:31)](https://youtu.be/S4QjN02TCQ4?t=9m31s)

## Tasks

- [x] Get merge stuff working with new can-diff and clean up other helpers to use can-reflect
- [x] Remove can-util from `can-connect` (makes can-connect more flexible)
- [x] Legacy support for `algebra` property in can-connect. `connect([..],{algebra})`
- [x] Maybe types  `{} \ {filter: {$gt:"bar"}} -> {filter: {foo: [{$lte: "bar"}, {$eq: null}]}}`
   - [x] Maybe Types working
   - [x] Maybe types working with can-define
- [x] Finish remaining comparators (example: `{$gt} U {$lte}`)
- [x] `can-rest-real-time` and `can-rest`
- [ ] Document can-connect
- [x] Document can-memory-store
- [x] Document can-query-logic
- [x] Document can-set-legacy
- [x] Document `identity` of `can-define` (maybe getSchema)
- [x] Document can-reflect.convert
- [x] Document can-diff
- [ ] Make fixtures support different data formats (Problem @bgando recently discovered)

## The Goals

1. Simplify configuration of connections and fixtures.
2. Expand the query logic that the default `can-set` is capable of.
3. Make a distinction between `isMember` and `subset` and make it easier to configure set logic itself.

## What easy mode looks like

The following is all that's needed if your service-layer matches what CanJS expects:

```js
// 1. DEFINE YOUR TYPE
import makeEnum from "can-types/make-enum/";
import types from "can-types";

const Status = makeEnum(["assigned","in-progress","complete", null])

const Todo = DefineMap.extend({
  id: {
    identity: true,
    type: Number
  },
  complete: types.MaybeBoolean,
  name: types.MaybeString,
  status: Status
});


// 2. CREATE YOUR CONNECTION
import realTimeRest from "can-real-time-rest";

realTimeRest({
  url: "/todos",
  Map: Todo
});


// 3. CREATE YOUR FIXTURE
fixture("/todos",Todo);


// 4. REQUEST DATA
Todo.getList({
  filter: {
    name: {$gt: "eat"},
    complete: true,
    status: ["assigned", "complete"]
  },
  sort: "name desc",
  page: {start: 10, end: 19}
})
```

For CanJS 5.0, this will support a service layer that is similar, but not exactly matching http://jsonapi.org/format/, with [mongo's comparison operators](https://docs.mongodb.com/manual/reference/operator/query-comparison/) `($eq, $gt, $gte, $in, $lt, $lte, $ne, $nin`).  Requests for a list of data will look like:

```js
{
  filter: {
    name: {$gt: "eat"},
    complete: true,
    status: ["assigned", "complete"]
  },
  sort: "name desc",
  page: {start: 10, end: 19}
}
```

This request data matches __JSONAPI__, but the response data does not match __JSONAPI__.  It continues to look like what `can-connect` expects:

```js
{
  "data": [
    {
      id: 5,
      name: "eat Tacos",
      complete: true,
      status: "assigned"
    },
    ...
  ],
  count: 500 // total number of
}
```

## Backwards Compatibility

We created a `can-set` compatibility module: `can-query/set-compat/set-compat`:

```js
// 1. DEFINE YOUR TYPE
const Todo = DefineMap.extend({...});


import set from "can-query/set-compat/set-compat";
var TodoQuery = new set.Algebra(
    new set.Translate("where","where"),
    set.props.id("_id"),
    set.props.sort('orderBy'),
    set.props.enum("type", ["used","new","certified"]),
    set.props.rangeInclusive("start","end")
);


// 2. CREATE YOUR CONNECTION
realTimeRest({
  url: "/todos",
  Map: Todo,
  query: TodoQuery
});


// 3. CREATE YOUR FIXTURE
fixture("/todos",TodoQuery);
```

### Request parameters don't match

The following changes `filter` to `where`:

```js
// 1. DEFINE YOUR TYPE
const Todo = DefineMap.extend({...});


var TodoQuery = new Query(Todo, function toQuery(params){
  var where = params.where;
  delete params.where;
  params.filter = where;
  return params;
}, function toParams(query){
  var where = query.filter;
  delete query.filter;
  query.where = where;
  return query;
})


// 2. CREATE YOUR CONNECTION
realTimeRest({
  url: "/todos",
  Map: Todo,
  query: TodoQuery
});


// 3. CREATE YOUR FIXTURE
fixture("/todos",TodoQuery);
```

### Special Comparison Logic

We will create a `SearchableString` type that can be specified like:

```js
const Todo = DefineMap.extend({
  id: {
    identity: true,
    type: Number
  },
  complete: types.MaybeBoolean,
  name: SearchableString,
  status: Status
});
```

It can be used to make requests that will match any
todo that contains the characters specified in name like:

```js
Todo.getList({
    filter: {name: "eat"}
})

/*->
  Promise<
     [ {id, name: "beat"}, {id, name: "eat beans"}]
  >
*/
```

```js
import set from "can-query/set/set";

// Create a set type that is used to do comparisons.
function SearchableStringSet(value) {
    this.value = value;
}
// Returns if the name on a todo is actually a member of the set.
SearchableStringSet.prototype[Symbol.for("can.isMember")] = function(value){
    return value.includes(this.value);
}

// Specify how to do the fundamental set comparisons.
set.defineComparison(SearchableStringSet,SearchableStringSet,{
    union(searchA, searchB){
        if(searchA.value.includes(searchB.value)) {
            return searchB;
        }
        if(searchB.value.includes(searchA.value)) {
            return searchA;
        }
        return new Or(searchA, searchB);
    },
    // a aa
    intersection(searchA, searchB){
        if(searchA.value.includes(searchB.value)) {
            return searchA;
        }
        if(searchB.value.includes(searchA.value)) {
            return searchB;
        }
        return set.UNDEFINABLE;
    },
    difference(searchA, searchB){
        // if a is a subset
        if(searchA.value.includes(searchB.value)) {
            return set.EMPTY;
        }
        // a is a superset
        if(searchB.value.includes(searchA.value)) {
            return set.UNDEFINABLE;
        }
        // foo \ bar
        return set.UNKNOWABLE;
    }
});

// Alternate comparisons
set.defineComparison(SearchableStringSet,SearchableStringSet,{
    isSubset(searchA, searchB){
        return searchA.value.includes(searchB.value);
    }
});

// The type specified doesn't do anything here.
// Sometimes it might be used for creating the actual value on
// a Todo. That's why it's only used for a reference ot the
// actual set type.
function SearchableString(){

}


SearchableString[Symbol.for("can.SetType")] = SearchableStringSet;
```

### 1. Define your types:

```js
Todo = DefineMap.extend({
  id: {
    identity: true,
    type: Number
  },
  complete: Boolean,
  name: String,
  status: makeEnum(["assigned","in-progress","complete"])
})
```

### 2. This creates a schema:

```js
var todoSchema = canReflect.getSchema(Todo);
todoSchema //-> {
  type: "map",
  identity: ["id"],
  properties: {
    id: Number,
    complete: Boolean,
    name: String,
    status: Status
  }
}
```

### 3. The schema is used by `can-query` to create set instances:

```js
var todoQuery = new Query(todoSchema);

todoQuery.union(
    { filter: {name: "assigned"} },
    { filter: {name: "complete"} }
)
```

These queries (`{ filter: {name: "assigned"} }`) are hydrated to set types like:

```js
var assignedSet = new BasicQuery({
    filter: new And({
        name: new Status[SetTypeSymbol]("assigned")
    })
});
```

Then `can-query/set` is used to perform the union:

```js
set.union(assignedSet, completeSet)
```

This will look for comparator functions specified on their constructor's
`can.setComparisons` symbol property:

```js
BasicQuery[can.setComparisons] = Map({
    [type1]: Map({[type2]: {union, difference, intersection}})
})
```

Types like `BasicQuery` and `And` are "composer" types.  Their
 `union`, `difference` and `intersection` methods will often perform
 `union`, `difference` and `intersection` on their children types.

In this case, `set.union` will call `BasicQuery`'s union with
itself.  This will see that the `sort` and `pagination` results match
and simply return a new `BasicQuery` with the union of the filters:

```js
new BasicQuery({
    filter: set.union( assignedSet.filter, completeSet.filter )
})
```

This will eventually result in a query like:

```js
new BasicQuery({
    filter: new And({
        name: new Status[SetTypeSymbol]("assigned", "complete")
    })
})
```

Finally, this set will be serialized to:

```js
{
    filter: {
        name: ["assigned", "complete"]
    }
}
```

And this is what is returned as a result of the union.

**Comment by BigAB** [comment]
## My First thought on initially reading it

So I am assuming a Maybe* type is basically a value of that type or null/undefined?
What happens if it receives a null for on a non-Maybe type? Does it throw?

---

RE: This part...

```js
var TodoQuery = new Query(Todo, function toQuery(params){
  var where = params.where;
  delete params.where;
  params.filter = where;
}, function toParams(query){
  var where = params.where;
  delete params.where;
  params.filter = where;
})
```

I am really into the `toQuery`/`toParams` transforms, but I thing you should take the returned value, because I like the idea of not mutating objects that do not belong to me.

--- 

I would like to know more about `set.defineComparison`, and the arguments it must receives, and what it does. It looks like it is stateful, as I assume the types are registered or something, but assuming the type is held in setType is help in the Model/Type definition I supposed that's alright.

---

Does the following syntax already work in DefineMaps (the type shorthand)?
```
Todo = DefineMap.extend({
  id: {
    identity: true,
    type: Number
  },
  complete: Boolean,
  name: String,
  status: makeEnum(["assigned","in-progress","complete"])
})
```

--- 

My **Favourite thing** about this:
```
fixture("/todos",TodoQuery);
```

My **Second Favourite** thing:
```
realTimeRest({
  url: "/todos",
  Map: Todo,
  query: TodoQuery
});
```

---

I've reached the end and I still don't know the distinction between isMember and subset.

---

This looks very promising. It is a problem with inherent complexity and therefore the solution will most likely be a little complex. It may be worth playing with the first implementation a bit, before releasing it, to see if there are areas we could simplify or combine, to make it easier for the end user.

Looks cool. I am down.

**Comment by justinbmeyer** [comment]
@BigAB 

> So I am assuming a Maybe* type is basically a value of that type or null/undefined?

Yes

> What happens if it receives a null for on a non-Maybe type? Does it throw?

Ideally yes, it will throw.  I'm not sure `can-define` is setup for this, but `can-observe` should work this way.

> I am really into the toQuery/toParams transforms, but I think you should take the returned value

It does, I wrote it wrong.  It's fixed now.   You can mutate these objects as a clone is passed to these functions.  But you need to return the value. 

> Does the following syntax already work in DefineMaps (the type shorthand)?

Not yet

> It may be worth playing with the first implementation a bit

I think I know what you mean here, but I'm not sure.  I would rather not play with the implementation past getting all our example apps working again.  It's an improvement over `can-set`.  It's important to release, get feedback, and move on.  

## More on defineComparison

`set.defineComparison` is basically a shorthand for an operator registry.  Instead of `===` and `<` being the operators, we register `union`, `intersection` and `difference`.  

It's only stateful as this helper makes an entry in the comparison map.  I showed this above:

```js
BasicQuery[can.setComparisons] = Map({
    [type1]: Map({[type2]: {union, difference, intersection}})
})
```

If you call `set.defineComparison(Foo, Bar, {union, difference, intersection})`, these functions get stored within a depth 2 tree keyed by the types being compared:

```js
Foo[can.setComparisons].get(Foo).set(Bar, {union, difference, intersection})
Bar[can.setComparisons].get(Bar).set(Foo, {union, intersection})
```

When `set.union`, etc is called, it looks up the types of the operands, and then looks in the types' `setComparisons` tree for how to perform the operator.

The `union`, `difference`, `intersection` methods should return  the result of performing a `union`, `difference`, `intersection`.

There are some special sets they can use:

- `set.EMPTY`
- `set.UNIVERSAL`
- `set.UNDEFINABLE`
- `set.UNKNOWABLE`

**Comment by justinbmeyer** [comment]
## The difference between is member and subset

`can-set` conflated the difference between a member and set.  In [set-theory](https://en.wikipedia.org/wiki/Set_theory) there is a difference:

- ∈ - member
- ⊆ - subset

This distinction matters as type properties don't always match query params 1 to 1.  For example, you might want to get all todos like:

```js
Todo.getList({searchText: "ice cream"})
```

A `Todo` doesn't have a `searchText` property.  So a __set__ like `{searchText: "ice cream"}` needs to be able to say if a __todo__ like `{id: 4, searchText: "make ice cream"}` is a member of the set.

There's a fundamental difference between a member of a set and comparing a set to another set.

**Comment by matthewp** [comment]
On swapping parameters:

The example shows:

```js
const Todo = DefineMap.extend({...});

function toParams(query){
  var where = query.filter;
  delete query.filter;
  query.where = where;
  return query;
}

function toQuery(params){
  var where = params.where;
  delete params.where;
  params.filter = where;
  return params;
}

var TodoQuery = new Query(Todo, toParams, toQuery);
```

If the conversion functions were the 1st two arguments you could use `.bind()` to create your own Query type:

__myquery.js__

```js
function toParams(query){
  var where = query.filter;
  delete query.filter;
  query.where = where;
  return query;
}

function toQuery(params){
  var where = params.where;
  delete params.where;
  params.filter = where;
  return params;
}

const MyQuery = Query.bind(null, toParams, toQuery);

export default MyQuery;
```

__todo.js__

```js
import Query from './my-query';

const Todo = DefineMap.extend({...});

// conversion functions are bound to Query so no need to pass them.
var TodoQuery = new Query(Todo);
```

**Comment by BigAB** [comment]
@matthewp's Idea seems good, because most likely all your API's will require that change, so it will b easier to use across 1 app

**Comment by BigAB** [comment]
...actually, why not take it a step further and if only the first 1 params are provided, do the binding for them and return a function.

**Comment by BigAB** [comment]
I would like to see an example of how you would write a service that had a `Date` type, and how the `$gte`, `$lte`, `$gt`, and `$lt` comparison operators would work, so that `can-fixture` would work, but the server (and can fixture) receive and respond with date strings like `2018-03-30T21:05:28.599Z`

**Comment by justinbmeyer** [comment]
@matthewp I was thinking instead:

```js
// feathers-service.js
module.exports = {
  toQuery() { ... },
  toParams(){ ... }
}
```

```js
new Query(Todo, featherService);
```

I like exporting this because it doesn't actually depend on `can-query`.  There are just functions. 
 These methods could be useful in other places in other ways.

**Comment by justinbmeyer** [comment]
@BigAB I'm not currently sure the __best__ way to _reuse_ the `gte` logic.  The following is a way that I know would work, but there's probably a lot we can do to make it easier:

```
DateSet = function(value){
  this.type = firstProp(value) // type will be "$gt", etc
  var value = value[this.type];
  var number = new Date(value).getTime();
  this.value = new comparisons[this.type](number); // this is creating a new $gt(123123123123)
}

set. defineComparison(DateSet, DateSet,{
  union: function(dateSet, dateSet) {
    var result = set.union(this.value, this.value);
    // convert result back to DateSet
    var dateString = new Date(result.value).toString();
    return new DateSet( {[result.type]: dateString});
  },
  ...
})
```

Basically, I'm making a DateSet convert to a $GT() with a number, and then back to a DateSet.

**Comment by matthewp** [comment]
@justinbmeyer The problem I was attempting to fix is having to provide that to every Query that gets made. Since it's the same (likely) for an entire application it would be nice to be able to bind it. It wouldn't be a problem if there was a `Function.prototype.rbind` or something. I guess people can use [`_.partialRight`](https://lodash.com/docs/4.17.5#partialRight).

**Comment by justinbmeyer** [comment]
So I'm trying to make an easy-ish way to reuse the `$gt`, etc logic as @BigAB requested.  I'm primarily focused on getting the "type" right and the easy part later.

The `valueOf` idea works for set comparisons, but it does not work for `isMember`.  

My idea was someone could create a type that doesn't have any of the `union`, `intersection`, `difference` comparators, and only exposes a `valueOf()` method.  `valueOf()` is already used for the `>`, `>=`, `<`, etc operators (but not `==`).  So if someone created a set type like:

```js
class DateStringSet {
  constructor(dateString){
    this.dateStr = dateStr;
  }
  valueOf(){
    return new Date(this.dateStr).valueOf();
  }
}
```

I'd make `GreaterThan`, `In`, etc all make sure to take the `valueOf()` before doing its comparisons.  

__The problem__ is that the `item` in `isMember` doesn't go through this conversion to set types.  For example:

```js
queryLogic.isMember(
  { filter: { date: {$gt: "2000-01-01"} } }, 
  {id: 0, name: "do something", date: "2018-03-30T21:05:28.599Z"})
```

The date in `{id: 0, name: "do something", date: "2018-03-30T21:05:28.599Z"}` is just passed to something like the following:

```js
var date2000 = new DateStringSet("2000-01-01")
new GreaterThan( date2000 ).isMember( "2018-03-30T21:05:28.599Z" )
```

We want the `GreaterThan` logic in `GreaterThan`, but we somehow need it to ask it's SetType instance to convert the `"2018-03-30T21:05:28.599Z"` to a value that `GreaterThan` can do a `>`.

One way of doing it would be for isMember to promote the value to match:

```js
GreaterThan = function(value){ this.value = value }
GreaterThan.prototype.isMember = function(value){
  return this.value.valueOf() > new this.value.constructor(value).valueOf();
}
```

Or it could check if the value provides some sort of conversion method itself:


```js
GreaterThan = function(value){ this.value = value }
GreaterThan.prototype.isMember = function(value){
  return this.value.valueOf() > new this.value.toValue(value);
}
```


I'm not sure the best way of making this work ...

**Comment by BigAB** [comment]
How about something like:
```js
import { connect, DefineMap } from "can";
const { rest, realtimeRest, superRest }  = connect;
```

**Comment by justinbmeyer** [comment]
Another option:

```js
import rest from "can-model-rest";
import realtimeRest from "can-model-realtime-rest";
import superRest from "can-model-super-rest";
import DefineMap from "can-define/map/map"
import {modelRest, modelRealtimeRest, modelSuperRest, DefineMap} from "can";

var Todo = DefineMap.extend({
        id: {type: "number", identity: true},
        name: "string",
        complete: "boolean",
        due: "date"
});

modelRest({Map: Todo, url: "/todos/{id}"})
modelRealtimeRest({Map: Todo, url: "/todos/{id}"})
modelSuperRest({Map: Todo, url: "/todos/{id}"})
```

**Comment by matthewp** [comment]
This is in 5.0-pre, so closing this issue.
