### ISSUE TITLE
CanJS 4.3

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4142]
This release will include everything for [Improve routing to components (and testing)](https://github.com/canjs/canjs/issues/4030).

Things that need release:

- [x] can-ajax (1.x-legacy)
- [x] can-assign
- [x] can-attribute-encoder
- [x] can-attribute-observable (need ownership)
- [x] can-bind
- [x] can-component
- [x] can-compute
- [x] can-connect
- [x] can-connect-feathers
- [x] can-construct
- [x] can-construct-super
- [x] can-control
- [x] can-debug
- [x] can-define
- [x] can-define-backup
- [x] can-define-lazy-value
- [x] can-define-stream
- [x] can-define-stream-kefir
- [x] can-define-validate-validatejs
- [x] can-deparam
- [x] can-diff (need ownership)
- [x] can-dom-events
- [x] can-dom-mutate
- [x] can-event-dom-enter
- [x] can-event-dom-radiochange
- [x] can-event-queue
- [x] can-fixture
- [x] can-fixture-socket
- [x] can-globals
- [x] can-kefir
- [x] can-key
- [x] can-key-tree
- [x] can-list
- [x] can-map
- [x] can-map-define
- [x] can-ndjson-stream (need ownership)
- [x] can-observation
- [x] can-observation-recorder
- [x] can-observe
- [x] can-param
- [x] can-parse-uri
- [x] can-reflect
- [x] can-reflect-dependencies
- [x] can-reflect-promise
- [x] can-route
- [x] can-route-pushstate
- [x] can-set
- [ ] can-simple-dom (already released?)
- [x] can-simple-map
- [x] can-simple-observable
- [x] can-stache
- [x] can-stache-bindings
- [x] can-stache-converters
- [x] can-stache-key
- [x] can-stache-route-helpers
- [x] can-stream
- [x] can-stream-kefir
- [x] can-string (need ownership)
- [x] can-types
- [x] can-util
- [x] can-validate
- [x] can-validate-legacy
- [x] can-validate-validatejs (need ownership)
- [x] can-value (release last)
- [x] can-vdom
- [x] can-view-autorender (4.x-legacy)
- [x] can-view-callbacks
- [x] can-view-import
- [x] can-view-live
- [x] can-view-nodelist
- [x] can-view-parser
- [x] can-view-scope
- [x] can-view-target
- [ ] can-zone (not going to release)

Site:

- [bit-docs-generate-html@0.11.0](https://github.com/bit-docs/bit-docs-generate-html/releases/tag/v0.11.0)

**Comment by chasenlehara** [comment]
We should make sure everything’s assigned to `can-namespace`; I know `can-assign` isn’t, and there might be others.
