### ISSUE TITLE
Debugging Guide Feedback

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#4718]
- [x] Image after `Clicking on a component in the tree will select it` should show component selected
  - Replace `panel-hover-on-component.png` with `panel-component-selected.png`
  - reword the transition to the next section

- [x] [The indentation of the ViewModel Editor is confusing](https://github.com/canjs/can-devtools-components/issues/78)

- [x] [weird spaces in editable-span component](https://github.com/canjs/can-devtools-components/issues/79)

- [x] [Apply changes not resetting](https://github.com/canjs/devtools/issues/68)

- [x] [Things break after a few refreshes](https://github.com/canjs/devtools/issues/69)
