### ISSUE TITLE
CanJS 6.0

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#4841]
CanJS 6.0 will:

- remove nodeLists (this will be the only breaking change)
- Use `DefineObject` and `StacheDefineElement`

## Tasks

- [x] Get prototype of component and dependencies working without nodelists
- [x] [Build target with comment nodes](https://github.com/canjs/can-stache/issues/701)
- [ ] [Fix importing with `steal-stache`.](https://github.com/canjs/can-view-import/issues/111)
- [ ] Get major version of `canjs/canjs` passing tests linking to branches.
- [ ] Make build pass all browsers.
- [x] Clean `can-queues`
- [ ] Remove unnecessary warnings
- [ ] Create a can-simple-object (doesn't use can-construct, only has Symbols on the prototype)
- [ ] Move things into core
- [ ] Make releases:
  - [x] can-dom-mutate
  - [ ] can-queues
  - [ ] can-observation
  - [ ] can-diff 
  - [ ] steal-stache
- [ ] Release CanJS

**Comment by Mattchewone** [comment]
In ref to - https://github.com/canjs/canjs/issues/4705

- `can-map` is using the `Symbol` and has latest can-construct
- `can-map-define` is using latest `can-map` and reading the `Symbol`
- `can-simple-map` is using the new `can-construct`
- `can-event-queue` is using both `Symbol` and `__inSetup` property

Left to do, update `can-define`, `can-map`, `can-map-define`, `can-simple-map` to use the new `can-event-queue`. Remove `__inSetup` property from `can-construct` and `can-event-queue`.

**Comment by justinbmeyer** [comment]
## Breaking Changes 

- "beforeRemove" is gone
- can-connect/can/tag is removed

**Comment by rjgotten** [comment]
@phillipskevin 
> CanJS 6.0 will:
> * remove nodeLists (this will be the only breaking change)
> * Use `DefineObject` and `StacheDefineElement`

`DefineObject` iirc uses `Proxy` which cannot be polyfilled. Would the end to being able to support Internet Explorer 11 through polyfills not also constitute a breaking change?

**Comment by phillipskevin** [comment]
@rjgotten thanks for asking. `ObservableObject` and `StacheElement` (the names changed a little) will not work in IE11, but we are not removing or dropping support for `can-define` and `can-component`. So if your app needs to support IE11, you can continue using these APIS.

**Comment by rjgotten** [comment]
Ok. That wasn't exactly clear. Thanks. :+1:

**Comment by phillipskevin** [comment]
Yeah, we'll make sure to make this clear in the migration guide (in progress now).
