### ISSUE TITLE
Data Guide: Working with sessions

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4861]
As part of the #4014 data guide issue, we should create a guide that details working with sessions. In addition, we should make some minor changes to CanJS to make working with sessions easier.

## Tasks

- [x] `can-ajax` work with a promise-based `beforeSend` - 3-4hrs (make beforeSend actually before send) [DONE](https://github.com/canjs/can-ajax/blob/87e0182bd9b9fab70c21e30a98b8fe12a3ce19c2/can-ajax.js#L267)
- [x] `data-url` `beforeSend` configuration ... document that - 3-4 hrs 
- [x] add docs for `can-define-singleton`
- [x] `can-connect/can/session/session` .. document that - 2-3 days - [can-connect-singleton](https://github.com/canjs/can-define-singleton). Make sure this is memory safe in SSR (can-zone-data?).
   - [x] fix can-connect/can/map needing a List type (done in restModel)
- [x] write guide

## Changes to CanJS

First, lets create an easy way to create session models.

```js
Session = DefineMap.extend({
});

import connectCanSession from "can-connect/can/session/session";

connect([restModelsBehaviors..., connectCanSession], {
  Map: Session
  // NO LIST IS OK ... 
  url: "/api/session",
  // JWT
  url: {
    getData(){ ... },
    createData() { ... }
  }
});
```

`connectCanSession` adds methods and properties to the passed in `Map` so that it's easy to create/delete/get a single instance:

```js
Session.current // First time it's read ... undefined, but kicks off a `Session.get()`

new Session({ ... }).save() //-> creates

Session.current.destroy() //-> delete, set Session.current to undefined

Session.currentPromise //-> resolved or rejected with the `Session.get()`
```

This should use [can-define-singleton](https://github.com/canjs/can-define-singleton) under the hood.

With the ability to get the singleton session object, we can make other connections include the session information when making request.  The following adds an `AUTH` header to all requests:

```js
import Session from "./session"

Player = DefineMap.extend({ ... })

realtimeRestModel({
  Map: Player,
  url: {
    resource: "/api/players",
    beforeSend(xhr){
       // waits for currentPromise to resolve before the XHR request is sent.
       return Session.currentPromise.then(function(session){
          xhr.setRequestHeader("AUTH",session.token);
       });
    }
  }
});
```

## Outline 

We should show how to setup the two most common use cases:

- CRUD with cookies
- CRUD with JWT

Show logging in, logging out, determining if there is a session, and making authenticated requests.  We might want to upgrade `Bitballs` to use this.
