### ISSUE TITLE
Remove deprecated APIs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#962]
This issue should serve as a catch-all for any deprecated APIs that should be removed in 3.0.  Please add to this list instead of creating a standalone issue.  Once it comes time to start working on this, we might break these off into their own issues.

- [ ] - Extending a can.Construct without calling extend.
- [x] - can.view.mustache and can.view.ejs (#2217)
- [x] - can.Model in favor of can-connect (#2218)
- [x] - direct properties on a can.Map
- [x] - Passing values to a component with mustache should use  `{}`
- [x] - Plugins that are no longer used (#2195):
  - [x] - can/map/attributes
  - [x] - can/map/setter
- [ ] - computes directly on the prototype of a can.Map
- [x] - defaults directly on the prototype of a can.Map (?)
- [x] - can/control/route #2164

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/canjs/issues/2026
